name: ci-golang-workflow
# on: [push]
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test ./goapp_aluno
      - run: go run ./goapp_aluno/math.go